import Tcs.Spec
import Tcs.Order
import Tcs.Count
import Tcs.Perm
import Tcs.Select
import Tcs.Sort
import Tcs.Cyclesort
import Tcs.Bfprt
import Tcs.Merge
import Tcs.UnstableMerge
import Tcs.Cost
import Tcs.Cost.Merge
import Tcs.Cost.Cyclesort
import Tcs.Cost.Sort
